#!/bin/bash
set -e
set -x
git push origin master
bundle exec nanoc compile
mkdir -p output/archives
rm output/archives/*.zip
zip -r output/archives/Infoshop.io.zip *
zip -r output/archives/Infoshop.zip content/media/*.pdf
cd site
git pull origin master
cp ../output/* .
git add -a
git commit -m "Updating site"
git push origin master