---
title: "Environmentalism has been Recycled"
summary: "Notes on Capitalism and Ecology"
date: "2009"
authors:
  - Sticks an Stones
languages: 
  - en
tags:
  - capitalism
  - sustainability
  - anarchism
---
